### ISSUE TITLE
Bug: Error when parsing "`"

### ISSUE THREAD

**Issue by fengh16** [rspivak/slimit#110]
The back quote("`") can't be parsed.

Example of input that caused error: 

``` javascript

function a() {
  var b = `b`;
}
```

Error message:

```
Illegal character '`' at 1:27 after LexToken(EQ,'=',1,25)
Illegal character '`' at 1:29 after LexToken(ID,'b',1,28)
```

**Comment by metatoaster** [comment]
`slimit` was written at a time when ES5 was the latest standard, which did not have backquotes (`` ` ``) as part of the syntax, as this was not introduced until ES6/ECMASript 2015 ([Section 11.8.6](https://www.ecma-international.org/ecma-262/6.0/#sec-template-literal-lexical-components)), so unfortunately, what you want to do is not currently supported by this library.

If parsing ECMAScript 2015 is the only requirement, try [esprima-python](https://github.com/Kronuz/esprima-python), which has support up to ECMAScript 2017.

**Comment by fengh16** [comment]
Thank you!
