### ISSUE TITLE
Unexpected token (SEMI, ';') at 1:1298 between ...

### ISSUE THREAD

**Issue by stodge** [rspivak/slimit#68]
I'm getting a syntax error from my javascript:

Unexpected token (SEMI, ';') at 1:1298 between LexToken(LINE_TERMINATOR,'\n',1,1295) and LexToken(CLASS,'class',1,1298)

It makes no sense - line number is 1 and the file doesn't contain the keyword "class" anywhere. jslint doesn't complain about anything in this file.

Any ideas how to identify what's causing this error? Thanks

**Comment by redyyu** [comment]
I had same issus

![screen shot 2015-07-10 at 5 57 59 am](https://cloud.githubusercontent.com/assets/724821/8607958/318abff8-26c9-11e5-87f7-898e697909c4.png)

the file is a angularjs file upload's lib. and it's work fine when using Nodejs's minify (grunt plugin).

I believe it is slimit's bug.
